# Generated by Django 4.1.2 on 2022-11-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_contains',
            name='unread_messages',
            field=models.BooleanField(default=True),
        ),
    ]
